apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  replicas: {{ .Values.postgresql.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
        - name: {{ .Release.Name }}-postgres
          image: {{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.db }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password }}
            - name: PGDATA
              value: /data/pgdata
  # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi

---

kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-postgres-svc
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.containerPort }}
  selector:
    app: {{ .Release.Name }}-postgres
