kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-builder
  labels:
    app: {{ .Release.Name }}-builder
spec:
  replicas: {{ .Values.builder.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-builder
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-builder
    spec:
      containers:
        - name: {{ .Release.Name }}-builder
          image: "{{ .Values.builder.image.registry }}/{{ .Values.builder.image.repository }}:{{ .Values.builder.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
---

kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-builder
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.builder.service.port }}
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}-builder
